// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDecjqeeey1RTzjwH3gR8cURq020NPL3d0',
    appId: '1:526607010232:web:81b1b3a0fc578703e5274d',
    messagingSenderId: '526607010232',
    projectId: 'prueba-firebase-7c331',
    authDomain: 'prueba-firebase-7c331.firebaseapp.com',
    storageBucket: 'prueba-firebase-7c331.firebasestorage.app',
    measurementId: 'G-MCZVHS4MCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkweJwwWEeBauxoc2wpfwBUMb3DM69qCk',
    appId: '1:526607010232:android:bbcc47de5522c87be5274d',
    messagingSenderId: '526607010232',
    projectId: 'prueba-firebase-7c331',
    storageBucket: 'prueba-firebase-7c331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmxvYrwiXv93LWlE1pkwa9OAizAciwbA',
    appId: '1:526607010232:ios:0769c7267646f7a7e5274d',
    messagingSenderId: '526607010232',
    projectId: 'prueba-firebase-7c331',
    storageBucket: 'prueba-firebase-7c331.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxmxvYrwiXv93LWlE1pkwa9OAizAciwbA',
    appId: '1:526607010232:ios:0769c7267646f7a7e5274d',
    messagingSenderId: '526607010232',
    projectId: 'prueba-firebase-7c331',
    storageBucket: 'prueba-firebase-7c331.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDecjqeeey1RTzjwH3gR8cURq020NPL3d0',
    appId: '1:526607010232:web:1a65b13cf61842ade5274d',
    messagingSenderId: '526607010232',
    projectId: 'prueba-firebase-7c331',
    authDomain: 'prueba-firebase-7c331.firebaseapp.com',
    storageBucket: 'prueba-firebase-7c331.firebasestorage.app',
    measurementId: 'G-HCL5M7XFHZ',
  );
}
